import { DynamicTool } from "@langchain/core/tools";
import nodemailer from 'nodemailer';

interface EmailInput {
  email: string;
  inquiry: string;
  answer: string;
}

// Create email transporter
const createTransporter = () => {
  return nodemailer.createTransport({
    service: 'gmail', // You can change this to your preferred email service
    auth: {
      user: process.env.EMAIL_USER, // Your email
      pass: process.env.EMAIL_PASS, // Your app password
    },
  });
};

// Custom email tool for sending answers to user inquiries
export const emailTool = new DynamicTool({
  name: "send_answer_to_user",
  description: `Send Xbox gaming answers directly to user's email address. 
  Use this tool when a user asks any Xbox gaming question and provides their email address.
  
  Input should be a JSON string with required fields:
  - 'email': user's email address
  - 'inquiry': user's original question
  - 'answer': complete answer to the user's question
  
  Example: {"email": "user@example.com", "inquiry": "What's the price of Xbox Series X?", "answer": "The Xbox Series X costs $499 and features 12 teraflops of GPU performance..."}
  
  Sample user prompts that should trigger this tool:
  - "What's the best Xbox console for gaming? Please email the answer to john@example.com"
  - "Can you tell me about Xbox Game Pass? My email is sarah@gmail.com"
  - "What are the latest Xbox games? Send details to mike@outlook.com"
  - "How much does Xbox Series X cost? Email me at user@test.com"
  - "What accessories do I need for Xbox? Please send to my email: gamer@domain.com"`,
  
  func: async (input: string) => {
    try {
      // Parse the input JSON
      let contactData: EmailInput;
      try {
        contactData = JSON.parse(input);
      } catch (parseError) {
        return "Error: Please provide contact details in JSON format with 'email', 'inquiry', and 'answer' fields.";
      }

      const { email, inquiry, answer } = contactData;

      // Validate input - all fields are mandatory
      if (!email || !inquiry || !answer) {
        return "Error: Email, inquiry, and answer are all required.";
      }

      // Email validation regex
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) {
        return "Error: Please provide a valid email address.";
      }

      // Check if email credentials are configured
      if (!process.env.EMAIL_USER || !process.env.EMAIL_PASS) {
        return "Error: Email service is not configured. Please contact support.";
      }

      const transporter = createTransporter();

      // Send answer email to user
      const mailOptions = {
        from: process.env.EMAIL_USER,
        to: email,
        subject: '🎮 Your Xbox Gaming Answer - Xbox Gaming Assistant',
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: linear-gradient(135deg, #107C41 0%, #0078d4 100%); padding: 30px; border-radius: 12px; text-align: center; color: white; margin-bottom: 20px;">
              <h1 style="margin: 0; font-size: 28px;">🎮 Xbox Gaming Assistant</h1>
              <p style="margin: 10px 0 0 0; font-size: 16px; opacity: 0.9;">Your Answer is Here!</p>
            </div>

            <div style="background-color: #f8f9fa; padding: 25px; border-radius: 8px; margin: 20px 0;">
              <h2 style="color: #333; margin-top: 0;">Your Question</h2>
              <div style="background-color: white; padding: 15px; border-radius: 6px; border-left: 4px solid #0078d4;">
                <p style="margin: 0; color: #333; font-style: italic;">"${inquiry}"</p>
              </div>
            </div>

            <div style="background-color: #e8f5e8; padding: 25px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #107C41;">
              <h2 style="color: #333; margin-top: 0;">My Answer</h2>
              <div style="background-color: white; padding: 15px; border-radius: 6px;">
                <p style="margin: 0; color: #333; line-height: 1.6;">${answer.replace(/\n/g, '<br>')}</p>
              </div>
            </div>

            <div style="background-color: #fff3cd; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #ffc107;">
              <h3 style="color: #333; margin-top: 0;">💡 Need More Help?</h3>
              <p style="margin: 5px 0; color: #333;">
                Have another Xbox gaming question? Feel free to ask me anytime!<br>
                I'm here to help with Xbox consoles, games, Game Pass, and more.
              </p>
            </div>

            <div style="margin-top: 30px; padding: 15px; background-color: #f1f1f1; border-radius: 8px; text-align: center;">
              <p style="margin: 0; font-size: 12px; color: #666;">
                Thank you for using Xbox Gaming Assistant!<br>
                Generated by Xbox Gaming Assistant • ${new Date().toLocaleString()}
              </p>
            </div>
          </div>
        `,
        text: `
🎮 Xbox Gaming Assistant - Your Answer

Your Question:
"${inquiry}"

My Answer:
${answer}

Need More Help?
Have another Xbox gaming question? Feel free to ask me anytime!
I'm here to help with Xbox consoles, games, Game Pass, and more.

Thank you for using Xbox Gaming Assistant!
Generated by Xbox Gaming Assistant • ${new Date().toLocaleString()}
        `.trim()
      };

      await transporter.sendMail(mailOptions);

      return `✅ Answer sent successfully!

Great news! I've sent your Xbox gaming answer directly to ${email}. Please check your inbox!

Your question: "${inquiry}"

Is there anything else about Xbox gaming, consoles, or services that I can help you with right now?`;
    } catch (error) {
      console.error('Email tool error:', error);
      
      if (error instanceof Error) {
        // Handle specific email errors
        if (error.message.includes('Invalid login')) {
          return "Error: Email authentication failed. Please contact support.";
        }
        if (error.message.includes('Network')) {
          return "Error: Network issue while sending email. Please try again later.";
        }
      }
      
      return "Error: Unable to send contact details at the moment. Please try again later or contact support directly.";
    }
  },
});
